### ISSUE TITLE
[Open Source Project] Clean up RtpMediaPlayer library

### ISSUE THREAD

**Issue by ashyonline** [creativa77/AndroidStreamingClient#29]

**Comment by ashyonline** [comment]
I'm currently doing some work here since I'm adding some javadoc documentation in the code.

**Comment by adamantivm** [comment]
:+1:

On Fri, Feb 20, 2015 at 5:12 PM, ashyonline <notifications@github.com>
wrote:

> I'm currently doing some work here since I'm adding some javadoc
> documentation in the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativa77/AndroidStreamingClient/issues/29#issuecomment-75310796>
> .
>



-- 
-- Julian Cerruti

**Comment by ashyonline** [comment]
I think the cleaning was good enough :)
