### ISSUE TITLE
Show RTP connection information in example

### ISSUE THREAD

**Issue by adamantivm** [creativa77/AndroidStreamingClient#44]
I think it would make it much easier for someone who gets started with this if the example application, when it starts, shows the key information necessary to stream video to this client.

For example, show the IP address and PORT where the streaming client is listening to.

Maybe other (hardcoded) data tips that could be useful: H.264, UDP, resolution?

**Comment by ashyonline** [comment]
https://github.com/creativa77/AndroidStreamingClient/pull/52
