### ISSUE TITLE
About the example program

### ISSUE THREAD

**Issue by ZhengzhongSun** [creativa77/AndroidStreamingClient#57]
Hi! It's very helpful for me.
I'm a little confused about the example program. Where is the input video of the example program? I run the example program, but there isn't a video in surface view. And I can't find an input in the code, how can I add an input video to the program?
Thank you!

Best wishes!
Dobbie

**Comment by ZhengzhongSun** [comment]
oh! I need to use Libstreaming as the input?

**Comment by adamantivm** [comment]
Hi @ZhengzhongSun. AndroidStreamingClient is only a client: it can only play back video.
We have used different tools for producing and streaming the video: libstreaming is one, but you can also try with VLC or mencoder if you wish.
Does that make sense?
Best,
Julian

**Comment by ZhengzhongSun** [comment]
But I didn't find that where should I put the uri of my video to the program?

**Comment by adamantivm** [comment]
It's been very long since I used this last but if I remember correct, on RTP you don't specify the URI on the client, instead you need to specify the target on the sender (i.e.: tell the broadcaster to which URI to broadcast to).

**Comment by adamantivm** [comment]
If you look in the readme, on the instructions on how to use libstreaming, it says where to configure the client IP address for libstreaming to stream to it.

**Comment by kjcxlab** [comment]
Client
====
1. I compiled the example in Androidstudio,and run it on my phone(meilan not2:android5.0);
2. Conneted to router.
3. IP:192.168.0.112

Server:
===== 
2. Then using the ffmpeg to stream a file named sintel.h264 to my client;
3. The cmd line:ffmpeg -re -i Sintel.h264 -vcodec copy -f rtp rtp://192.168.0.112:5006

But:
===
Nothing in surfaceview 

Logcat
=====
01-23 10:15:01.130 24672-24700/net.kjcxlab.wificar W/RtpMediaDecoder: Ssrc changed, restarting decoder
01-23 10:15:01.132 24672-24696/net.kjcxlab.wificar E/RtpMediaDecoder: Exiting thread through interruption
                                                                      java.lang.InterruptedException
                                                                          at java.lang.Thread.sleep(Native Method)
                                                                          at java.lang.Thread.sleep(Thread.java:1031)
                                                                          at java.lang.Thread.sleep(Thread.java:985)
                                                                          at com.c77.androidstreamingclient.lib.rtp.RtpMediaDecoder$RTPClientThread.run(RtpMediaDecoder.java:414)
01-23 10:15:01.178 24672-24828/net.kjcxlab.wificar W/cbes.AbstractRtpSession: First packet received from remote source, updated SSRC to 1127028363.
01-23 10:15:01.855 24672-24687/net.kjcxlab.wificar W/art: Suspending all threads took: 7.277ms

**Comment by kjcxlab** [comment]
working:
======
I found the video size must be 640*480;
so,i reformate the sintel.mp4 to 640*480
 but i thinking we don't need hardcode a video info in another way;

**Comment by adamantivm** [comment]
Please feel free to send PR with any recommendations or additions to the readme instructions, samples or library in order to make it better!
Also note we are going to rename the organization today. It shouldn't affect your work, but just letting you know so that you're aware.

**Comment by adamantivm** [comment]
Closing the issue since it doesn't seem to have questions (particularly concrete bug reports) pending.
