### ISSUE TITLE
PS stream

### ISSUE THREAD

**Issue by OneDayNoMore** [creativa77/AndroidStreamingClient#63]
Can I play PS stream?

**Comment by adamantivm** [comment]
What do you mean? Play Station? What's the format?

**Comment by OneDayNoMore** [comment]
H264 package in the PS stream, if you directly use your demo, will be green screen

**Comment by adamantivm** [comment]
That means it's close to working. It may be that the codec used in the stream is not supported by the combination of Android phone and configuration used.
I can suggest the following:
 - Look into the logcat to see if you can tell what exactly the imcompatibility is
 - Try to get more information about the stream. H264 is only a packaging format. There should also be a video codec at least, and probably more information. Maybe use another professional player to get this information.
 - Use the source code of the demo to look at the decoder configuration and see if you can fis the problem

**Comment by OneDayNoMore** [comment]
Thank you for your answer, I have found the answer, because I get the data in the H264 package PS format, PS header, your Demo does not support this unpacking function, still thank you

**Comment by adamantivm** [comment]
If you are interested in doing a modification to the code to support this format, I will be very happy to review and accept a pull request, so that the demo will support it in the future.
